project:
  title: "Dyerlab-Template"
  output-dir: docs
  
format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    html-math-method: katex
    self-contained: false
    code-block-border-left: "#31BAE9"
    citations-hover: true
    footnotes-hover: true
    link-external-icon: true